import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { PageShell } from "@/components/page-shell";
import { COURSES } from "@/data";
import { jsonLd, pageMetadata } from "@/lib/seo";
export function generateStaticParams() { return COURSES.map((course) => ({ slug: course.slug })); }
export function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { return params.then(({ slug }) => { const course = COURSES.find((item) => item.slug === slug); return course ? pageMetadata(course.title, course.description, `/${course.slug}`) : {}; }); }
function parentPath(pillar: string) { if (pillar === "Technology Training") return "/technology-training"; if (pillar === "ISO, Standards and GRC") return "/iso-standards-training"; if (pillar === "Management Systems and Frameworks") return "/itil-prince2-agile-training"; return "/leadership-soft-skills-training"; }
export default async function CoursePage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const course = COURSES.find((item) => item.slug === slug); if (!course) notFound(); return <PageShell title={course.title} intro={course.description} breadcrumbs={[{ label: course.pillar, href: parentPath(course.pillar) }, { label: course.title }]}><section className="mt-16 grid gap-12 border-b border-[#cfd5df] pb-16 lg:grid-cols-[0.85fr_1.15fr]"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#bd6d38]">A direct answer</p><h2 className="mt-4 text-3xl font-extrabold tracking-[-0.04em]">What is {course.title}?</h2></div><p className="text-lg leading-relaxed text-slate-600">This program is intended for {course.audience.toLowerCase()} TraininGenie uses a requirements-driven approach so the emphasis, examples, and delivery can be aligned to the team context.</p></section><section className="grid gap-12 border-b border-[#cfd5df] py-16 lg:grid-cols-[0.85fr_1.15fr]"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#bd6d38]">What participants learn</p><h2 className="mt-4 text-3xl font-extrabold tracking-[-0.04em]">A practical programme shaped around the requirement.</h2></div><ul className="border-t border-[#cfd5df]">{course.topics.map((topic, index) => <li key={topic} className="grid grid-cols-[48px_1fr] border-b border-[#cfd5df] py-4 text-[17px]"><span className="text-sm font-bold text-[#bd6d38]">{String(index + 1).padStart(2, "0")}</span><span className="font-semibold text-slate-700">{topic}</span></li>)}</ul></section><section className="grid gap-10 border-b border-[#cfd5df] py-16 md:grid-cols-2"><div><h2 className="text-2xl font-extrabold">How is the program customized?</h2><p className="mt-4 leading-relaxed text-slate-600">Standard offerings can be fine-tuned to specific requirements. Discuss the audience, business objective, and preferred format with TraininGenie to explore a suitable approach.</p></div><div><h2 className="text-2xl font-extrabold">Next steps</h2><p className="mt-4 leading-relaxed text-slate-600">Program duration, delivery mode, pricing, and certification or examination arrangements should be confirmed for the specific engagement.</p><Link href="/contact-us" className="mt-6 inline-flex rounded-full bg-[#0e1726] px-6 py-3 text-sm font-bold text-white">Ask about this programme</Link></div></section>{jsonLd({ "@context": "https://schema.org", "@type": "Course", name: course.title, description: course.description, provider: { "@type": "Organization", name: "TraininGenie", url: "https://www.trainingenie.com" } })}</PageShell>; }
