import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { PageShell } from "@/components/page-shell";
import { COURSE_DETAILS, COURSES, SITE_URL } from "@/data";
import { jsonLd, ORGANIZATION_ID, pageMetadata } from "@/lib/seo";
import { buttonPrimary, eyebrow } from "@/lib/ui";
export function generateStaticParams() { return COURSES.map((course) => ({ slug: course.slug })); }
export function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { return params.then(({ slug }) => { const course = COURSES.find((item) => item.slug === slug); return course ? pageMetadata(course.title, course.description, `/${course.slug}`) : {}; }); }
function parentPath(pillar: string) { if (pillar === "Technology Training") return "/technology-training"; if (pillar === "ISO, Standards and GRC") return "/iso-standards-training"; if (pillar === "Management Systems and Frameworks") return "/itil-prince2-agile-training"; return "/leadership-soft-skills-training"; }
// "ISO 27001 Training" -> "ISO 27001", "ReactJS Corporate Training" -> "ReactJS"
function subjectOf(title: string) { return title.replace(/( Corporate)? (Training|Workshop)$/, ""); }
const heading = "mt-4 text-3xl font-extrabold tracking-[-0.04em]";
const row = "grid gap-12 border-b border-border py-16 lg:grid-cols-[0.85fr_1.15fr]";
export default async function CoursePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const course = COURSES.find((item) => item.slug === slug); const detail = COURSE_DETAILS[slug]; if (!course || !detail) notFound();
  const subject = subjectOf(course.title); const url = `${SITE_URL}/${course.slug}`; const related = detail.related.map((item) => COURSES.find((other) => other.slug === item)).filter((item) => item !== undefined);
  return <PageShell title={course.title} intro={course.description} breadcrumbs={[{ label: course.pillar, href: parentPath(course.pillar) }, { label: course.title }]}>
    <section className="mt-16 grid gap-12 border-b border-border pb-16 lg:grid-cols-[0.85fr_1.15fr]"><div><p className={eyebrow}>A direct answer</p><h2 className={heading}>What is {subject}?</h2></div><div className="space-y-5 text-lg leading-relaxed text-slate-600">{detail.overview.map((paragraph) => <p key={paragraph.slice(0, 40)}>{paragraph}</p>)}</div></section>
    <section className={row}><div><p className={eyebrow}>What participants learn</p><h2 className={heading}>Key concepts covered</h2><p className="mt-5 leading-relaxed text-slate-600">The emphasis, examples, and exercises are shaped around the team&apos;s context and objectives.</p></div><ol className="border-t border-border">{detail.concepts.map((concept, index) => <li key={concept.name} className="grid grid-cols-[48px_1fr] border-b border-border py-5"><span className="text-sm font-bold text-accent">{String(index + 1).padStart(2, "0")}</span><div><h3 className="text-[17px] font-bold text-slate-800">{concept.name}</h3><p className="mt-1.5 leading-relaxed text-slate-600">{concept.detail}</p></div></li>)}</ol></section>
    <section className="grid gap-10 border-b border-border py-16 md:grid-cols-2"><div><p className={eyebrow}>Who should attend</p><h2 className="mt-4 text-2xl font-extrabold">Designed for</h2><p className="mt-4 text-lg leading-relaxed text-slate-600">{course.audience}</p></div><div><p className={eyebrow}>Outcomes</p><h2 className="mt-4 text-2xl font-extrabold">After the programme, participants can</h2><ul className="mt-4 space-y-3">{detail.outcomes.map((outcome) => <li key={outcome} className="flex gap-3 leading-relaxed text-slate-600"><span aria-hidden="true" className="mt-2.5 h-1.5 w-1.5 shrink-0 rounded-full bg-accent" />{outcome}</li>)}</ul></div></section>
    <section className="grid gap-10 border-b border-border py-16 md:grid-cols-2"><div><h2 className="text-2xl font-extrabold">How is the programme customized?</h2><p className="mt-4 leading-relaxed text-slate-600">TraininGenie uses a requirements-driven approach. Standard offerings can be fine-tuned to specific requirements: discuss the audience, business objective, and preferred format to explore a suitable approach.</p></div><div><h2 className="text-2xl font-extrabold">Next steps</h2><p className="mt-4 leading-relaxed text-slate-600">Programme duration, delivery mode, pricing, and certification or examination arrangements should be confirmed for the specific engagement.</p><Link href="/contact-us" className={`${buttonPrimary} mt-6`}>Ask about this programme</Link></div></section>
    <section className={row}><div><p className={eyebrow}>Questions</p><h2 className={heading}>{subject} training FAQs</h2></div><div className="divide-y divide-border border-y border-border">{detail.faqs.map(([question, answer]) => <div key={question} className="py-6"><h3 className="text-lg font-bold text-slate-800">{question}</h3><p className="mt-2 leading-relaxed text-slate-600">{answer}</p></div>)}</div></section>
    <section className="py-16"><p className={eyebrow}>Related programmes</p><div className="mt-6 grid gap-6 md:grid-cols-3">{related.map((item) => <Link key={item.slug} href={`/${item.slug}`} className="group border-t border-border pt-4"><h3 className="text-lg font-bold text-foreground group-hover:text-primary group-hover:underline">{item.title}</h3><p className="mt-2 text-sm leading-relaxed text-slate-600">{item.description}</p></Link>)}</div><Link href={parentPath(course.pillar)} className="mt-10 inline-flex font-bold text-primary underline underline-offset-4">All {course.pillar} training</Link></section>
    {jsonLd({ "@context": "https://schema.org", "@type": "Course", "@id": `${url}#course`, name: course.title, description: course.description, url, inLanguage: "en-IN", teaches: detail.concepts.map((concept) => concept.name), audience: { "@type": "Audience", audienceType: course.audience }, provider: { "@type": "Organization", "@id": ORGANIZATION_ID, name: "TraininGenie", url: SITE_URL } })}
    {jsonLd({ "@context": "https://schema.org", "@type": "FAQPage", "@id": `${url}#faq`, url, mainEntity: detail.faqs.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) })}
  </PageShell>;
}
