import type { Metadata } from "next";
import Link from "next/link";
import { PageShell } from "@/components/page-shell";
import { PAST_TRAININGS } from "@/data";
import { pageMetadata } from "@/lib/seo";
export const metadata: Metadata = pageMetadata("Past Trainings", "Past corporate training topics delivered by TraininGenie, including SAP DRC, Advanced Excel and VBA, agentic AI for finance, AI tools for procurement, leadership development, team building, and Design Thinking.", "/past-trainings");
// What each topic covers, and the catalogue page it belongs to. Describes the subject only, not any specific client engagement.
const TOPIC_CONTEXT: Record<string, { about: string; href: string; area: string }> = {
  "SAP Document and Reporting Compliance readiness": { about: "Preparing finance and ERP teams for SAP Document and Reporting Compliance (DRC), the SAP solution for electronic invoicing and statutory reporting requirements.", href: "/technology-training", area: "Technology training" },
  "Leadership development programmes": { about: "Building leadership capability across communication, coaching, decision making, and leading high-performing teams.", href: "/leadership-soft-skills-training", area: "Leadership and soft skills" },
  "VBA macros for Excel": { about: "Automating repetitive Excel work with VBA macros, from recording simple macros to writing and maintaining reusable code.", href: "/technology-training", area: "Technology training" },
  "Advanced Excel": { about: "Advanced formulas, lookups, PivotTables, data analysis, and modelling techniques for business users who work with data every day.", href: "/technology-training", area: "Technology training" },
  "Agentic AI for finance": { about: "How AI agents that plan and carry out multi-step tasks can support finance workflows, along with the controls and judgement needed to use them responsibly.", href: "/technology-training", area: "Technology training" },
  "AI tools in Excel and PowerPoint for procurement": { about: "Using AI assistants inside Excel and PowerPoint to speed up procurement analysis, reporting, and presentations.", href: "/technology-training", area: "Technology training" },
  "Experiential team building": { about: "Activity-based sessions that strengthen collaboration, trust, and collective problem solving within and across teams.", href: "/leadership-soft-skills-training", area: "Leadership and soft skills" },
  "Design Thinking workshop": { about: "A facilitated, human-centred approach to understanding users, framing problems, and prototyping and testing ideas.", href: "/design-thinking-workshop", area: "Design Thinking workshop" },
};
export default function Page() { return <PageShell title="Past Trainings" intro="A selection of past training topics delivered by TraininGenie, spanning business tools, ERP and AI, leadership, team effectiveness, and innovation."><section className="mt-16"><div className="border-t border-border">{PAST_TRAININGS.map((training) => { const context = TOPIC_CONTEXT[training.title]; return <article key={training.title} className="grid gap-4 border-b border-border py-8 md:grid-cols-[0.6fr_0.4fr] md:items-start"><div><h2 className="text-2xl font-medium tracking-[-0.03em]">{training.title}</h2>{context && <p className="mt-3 max-w-xl leading-relaxed text-slate-600">{context.about}</p>}</div><div><div className="flex flex-wrap gap-x-5 gap-y-2 text-sm text-slate-600 max-md:justify-center">{training.tags.map((tag) => <span key={tag}>{tag}</span>)}</div>{context && <Link href={context.href} className="mt-4 inline-flex text-sm font-bold text-primary underline underline-offset-4">{context.area}</Link>}</div></article>; })}</div></section><section className="mt-16 border-t border-border pt-12"><p className="max-w-2xl text-lg leading-relaxed text-slate-600">Each new programme is shaped around the organization, the audience, and the desired outcome. <Link href="/contact-us" className="font-bold text-primary underline underline-offset-4">Discuss a similar programme</Link> for your team.</p></section></PageShell>; }
