import type { Metadata } from "next";
import "./globals.css";
import { plusJakarta } from "./fonts";
import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";
import { COMPANY_DESCRIPTION, COMPANY_NAME, SITE_URL, CONTACT_INFO, TRAINING_PILLARS } from "@/data";
import { jsonLd, SEO_KEYWORDS } from "@/lib/seo";
export const metadata: Metadata = { metadataBase: new URL(SITE_URL), title: { default: `${COMPANY_NAME} | Corporate Training and Learning`, template: `%s | ${COMPANY_NAME}` }, description: COMPANY_DESCRIPTION, keywords: SEO_KEYWORDS, authors: [{ name: "Mousumi Chakraborty" }], creator: COMPANY_NAME, publisher: COMPANY_NAME, category: "Business training and education", alternates: { canonical: SITE_URL }, openGraph: { siteName: COMPANY_NAME, type: "website", url: SITE_URL, title: `${COMPANY_NAME} | Corporate Training and Learning`, description: COMPANY_DESCRIPTION, locale: "en_IN", images: [{ url: "/opengraph.jpg", width: 1200, height: 630, alt: `${COMPANY_NAME} corporate training` }] }, twitter: { card: "summary_large_image", title: `${COMPANY_NAME} | Corporate Training and Learning`, description: COMPANY_DESCRIPTION, images: ["/opengraph.jpg"] }, robots: { index: true, follow: true, googleBot: { index: true, follow: true, "max-image-preview": "large", "max-snippet": -1, "max-video-preview": -1 } } };
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) { return <html lang="en-IN"><body className={plusJakarta.variable}><Navbar /><main>{children}</main><Footer />{jsonLd({ "@context": "https://schema.org", "@graph": [{ "@type": "Organization", "@id": `${SITE_URL}/#organization`, name: COMPANY_NAME, url: SITE_URL, logo: `${SITE_URL}/logo_dark.png`, description: COMPANY_DESCRIPTION, email: CONTACT_INFO.email, telephone: CONTACT_INFO.phones, founder: { "@type": "Person", name: "Mousumi Chakraborty", jobTitle: "Founder Director", sameAs: CONTACT_INFO.directorLinkedIn }, areaServed: ["Bengaluru", "Kolkata", "India"], knowsAbout: SEO_KEYWORDS.filter((keyword) => keyword !== COMPANY_NAME), hasOfferCatalog: { "@type": "OfferCatalog", name: "Corporate training catalogue", itemListElement: TRAINING_PILLARS.map((pillar, index) => ({ "@type": "Offer", position: index + 1, name: pillar.title, description: pillar.description, url: `${SITE_URL}/${pillar.slug}` })) }, contactPoint: { "@type": "ContactPoint", contactType: "sales", email: CONTACT_INFO.email, telephone: CONTACT_INFO.phones[0], areaServed: "IN", availableLanguage: ["English", "Hindi", "Bengali", "Odia"] }, sameAs: [CONTACT_INFO.companyLinkedIn, CONTACT_INFO.directorLinkedIn] }, { "@type": "WebSite", "@id": `${SITE_URL}/#website`, name: COMPANY_NAME, url: SITE_URL, description: COMPANY_DESCRIPTION, publisher: { "@id": `${SITE_URL}/#organization` }, inLanguage: "en-IN", potentialAction: { "@type": "ReadAction", target: SITE_URL } }] })}</body></html>; }
