import type { Metadata } from "next";
import "./globals.css";
import { plusJakarta } from "./fonts";
import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";
import { COMPANY_DESCRIPTION, COMPANY_NAME, COMPANY_TAGLINE, SITE_URL, CONTACT_INFO, TRAINING_PILLARS } from "@/data";
import { BRAND_ALTERNATE_NAMES, FOUNDER_ID, jsonLd, ORGANIZATION_ID, SEO_KEYWORDS, WEBSITE_ID } from "@/lib/seo";
// Search console ownership tags. Set these in the hosting environment; nothing is emitted when they are unset.
const verification: Metadata["verification"] = { google: process.env.GOOGLE_SITE_VERIFICATION, other: process.env.BING_SITE_VERIFICATION ? { "msvalidate.01": process.env.BING_SITE_VERIFICATION } : undefined };
export const metadata: Metadata = { metadataBase: new URL(SITE_URL), applicationName: COMPANY_NAME, title: { default: `${COMPANY_NAME} | Corporate Training and Learning`, template: `%s | ${COMPANY_NAME}` }, description: COMPANY_DESCRIPTION, keywords: SEO_KEYWORDS, authors: [{ name: "Mousumi Chakraborty", url: `${SITE_URL}/our-team` }], creator: COMPANY_NAME, publisher: COMPANY_NAME, category: "Business training and education", verification, alternates: { canonical: SITE_URL }, openGraph: { siteName: COMPANY_NAME, type: "website", url: SITE_URL, title: `${COMPANY_NAME} | Corporate Training and Learning`, description: COMPANY_DESCRIPTION, locale: "en_IN" }, twitter: { card: "summary_large_image", title: `${COMPANY_NAME} | Corporate Training and Learning`, description: COMPANY_DESCRIPTION }, robots: { index: true, follow: true, googleBot: { index: true, follow: true, "max-image-preview": "large", "max-snippet": -1, "max-video-preview": -1 } } };
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) { return <html lang="en-IN"><body className={plusJakarta.variable}><Navbar /><main>{children}</main><Footer />{jsonLd({ "@context": "https://schema.org", "@graph": [{ "@type": "Organization", "@id": ORGANIZATION_ID, name: COMPANY_NAME, alternateName: BRAND_ALTERNATE_NAMES, url: SITE_URL, logo: { "@type": "ImageObject", url: `${SITE_URL}/logo_dark.png`, width: 380, height: 430 }, image: `${SITE_URL}/logo_dark.png`, slogan: COMPANY_TAGLINE, description: COMPANY_DESCRIPTION, email: CONTACT_INFO.email, telephone: CONTACT_INFO.phones, address: { "@type": "PostalAddress", addressLocality: "Bengaluru", addressRegion: "Karnataka", addressCountry: "IN" }, founder: { "@id": FOUNDER_ID }, areaServed: ["Bengaluru", "Kolkata", "India"], knowsAbout: SEO_KEYWORDS.filter((keyword) => keyword !== COMPANY_NAME && keyword !== "Training Genie"), hasOfferCatalog: { "@type": "OfferCatalog", name: "Corporate training catalogue", itemListElement: TRAINING_PILLARS.map((pillar, index) => ({ "@type": "Offer", position: index + 1, name: pillar.title, description: pillar.description, url: `${SITE_URL}/${pillar.slug}` })) }, contactPoint: { "@type": "ContactPoint", contactType: "sales", email: CONTACT_INFO.email, telephone: CONTACT_INFO.phones[0], url: `${SITE_URL}/contact-us`, areaServed: "IN", availableLanguage: ["English", "Hindi", "Bengali", "Odia"] }, sameAs: [CONTACT_INFO.companyLinkedIn] }, { "@type": "Person", "@id": FOUNDER_ID, name: "Mousumi Chakraborty", jobTitle: "Founder Director", url: `${SITE_URL}/our-team`, worksFor: { "@id": ORGANIZATION_ID }, homeLocation: { "@type": "Place", name: "Bengaluru, India" }, knowsLanguage: ["English", "Hindi", "Bengali", "Odia"], sameAs: [CONTACT_INFO.directorLinkedIn] }, { "@type": "WebSite", "@id": WEBSITE_ID, name: COMPANY_NAME, alternateName: BRAND_ALTERNATE_NAMES, url: `${SITE_URL}/`, description: COMPANY_DESCRIPTION, publisher: { "@id": ORGANIZATION_ID }, inLanguage: "en-IN" }] })}</body></html>; }
