import type { Metadata } from "next";
import "./globals.css";
import { plusJakarta } from "./fonts";
import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";
import { COMPANY_DESCRIPTION, COMPANY_NAME, SITE_URL, CONTACT_INFO } from "@/data";
import { jsonLd } from "@/lib/seo";
export const metadata: Metadata = { metadataBase: new URL(SITE_URL), title: { default: `${COMPANY_NAME} | Corporate Training and Learning`, template: `%s | ${COMPANY_NAME}` }, description: COMPANY_DESCRIPTION, authors: [{ name: "Mousumi Chakraborty" }], creator: COMPANY_NAME, publisher: COMPANY_NAME, alternates: { canonical: SITE_URL }, icons: { icon: "/logo_dark.png", shortcut: "/logo_dark.png", apple: "/logo_dark.png" }, openGraph: { siteName: COMPANY_NAME, type: "website", url: SITE_URL, title: `${COMPANY_NAME} | Corporate Training and Learning`, description: COMPANY_DESCRIPTION, images: [{ url: "/opengraph.jpg", width: 1200, height: 630, alt: `${COMPANY_NAME} corporate training` }] }, twitter: { card: "summary_large_image", title: `${COMPANY_NAME} | Corporate Training and Learning`, description: COMPANY_DESCRIPTION, images: ["/opengraph.jpg"] }, robots: { index: true, follow: true, googleBot: { index: true, follow: true, "max-image-preview": "large", "max-snippet": -1, "max-video-preview": -1 } } };
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) { return <html lang="en"><body className={plusJakarta.variable}><Navbar /><main>{children}</main><Footer />{jsonLd({ "@context": "https://schema.org", "@graph": [{ "@type": "Organization", "@id": `${SITE_URL}/#organization`, name: COMPANY_NAME, url: SITE_URL, logo: `${SITE_URL}/logo_dark.png`, description: COMPANY_DESCRIPTION, email: CONTACT_INFO.email, telephone: CONTACT_INFO.phones, founder: { "@type": "Person", name: "Mousumi Chakraborty", jobTitle: "Founder Director" }, areaServed: ["Bengaluru", "Kolkata", "India"], sameAs: ["https://www.linkedin.com/company/trainingenie/", "https://www.linkedin.com/in/mousumi-chakraborty-468b1916/"] }, { "@type": "WebSite", "@id": `${SITE_URL}/#website`, name: COMPANY_NAME, url: SITE_URL, description: COMPANY_DESCRIPTION, publisher: { "@id": `${SITE_URL}/#organization` }, inLanguage: "en-IN" }] })}</body></html>; }
