import Link from "next/link";
import { CatalogueSection } from "@/components/catalogue-section";
import { BEHAVIORAL_GROUPS, FRAMEWORK_GROUPS, ISO_GROUPS, TECHNOLOGY_GROUPS } from "@/data";
import { jsonLd } from "@/lib/seo";

export default function Home() {
  return <div className="bg-[#f7f8fa] text-[#0e1726]">
    <section className="relative overflow-hidden border-b border-[#cfd5df] px-5 pb-24 pt-40 sm:px-8 md:pb-32 md:pt-52"><div className="absolute inset-0 -z-10 bg-[linear-gradient(to_right,#80808012_1px,transparent_1px),linear-gradient(to_bottom,#80808012_1px,transparent_1px)] bg-[size:48px_48px]" /><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.1fr_0.9fr] lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-[#bd6d38]">Corporate learning and development</p><h1 className="mt-6 max-w-4xl text-5xl font-extrabold leading-[1.03] tracking-[-0.06em] sm:text-7xl">Transcend Beyond Growth</h1></div><div className="max-w-xl lg:pb-2"><p className="text-lg leading-relaxed text-slate-600 md:text-xl">Practical learning experiences for teams building capability across technology, leadership, business tools, management systems, standards, and governance.</p><div className="mt-8 flex flex-wrap gap-4"><Link href="/corporate-training-services" className="rounded-full bg-[#0e1726] px-6 py-3 text-sm font-bold text-white hover:bg-[#1d2a63]">Explore training topics</Link><Link href="/contact-us" className="rounded-full border border-[#aeb6c4] px-6 py-3 text-sm font-bold text-[#0e1726] hover:bg-white">Discuss your training needs</Link></div></div></div></section>
    <main className="mx-auto max-w-7xl px-5 sm:px-8"><div className="py-20 md:py-28"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#bd6d38]">The training directory</p><h2 className="mt-4 text-4xl font-extrabold tracking-[-0.05em] sm:text-5xl">A broad capability, organized for clarity.</h2><p className="mt-5 text-lg leading-relaxed text-slate-600">Browse the major areas of learning supported by TraininGenie. Each programme can be adapted around the organization, the participants, and the outcome.</p></div><div className="mt-4"><CatalogueSection number="01" eyebrow="Technology" title="Technology Training" intro="Technical learning across infrastructure, software engineering, data, emerging technology, security, and networks." groups={TECHNOLOGY_GROUPS} href="/technology-training" /><CatalogueSection number="02" eyebrow="People and performance" title="Leadership and Soft Skills" intro="Practical programmes for leadership, communication, collaboration, workplace effectiveness, and team performance." groups={BEHAVIORAL_GROUPS} href="/leadership-soft-skills-training" /><CatalogueSection number="03" eyebrow="Delivery and management" title="Management Systems and Frameworks" intro="Shared approaches for service management, project delivery, agile ways of working, and organizational change." groups={FRAMEWORK_GROUPS} href="/itil-prince2-agile-training" /><CatalogueSection number="04" eyebrow="Standards and governance" title="ISO, Standards and GRC" intro="Learning across quality, information security, service continuity, risk, governance, privacy, and compliance." groups={ISO_GROUPS} href="/iso-standards-training" /></div></div>
      <section className="grid gap-12 border-t border-[#cfd5df] py-20 md:grid-cols-2 md:py-28"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#bd6d38]">Why this approach</p><h2 className="mt-4 text-4xl font-extrabold tracking-[-0.05em]">Start with the requirement. Work backward from the outcome.</h2></div><div className="space-y-5 text-lg leading-relaxed text-slate-600"><p>The approach begins by understanding the client problem and the desired outcome.</p><p>That context shapes the learning experience, the activities, and the practical application.</p><Link href="/training-methodology" className="text-base font-bold text-[#1d2a63] underline underline-offset-4">See the methodology</Link></div></section>
      <section className="grid gap-12 border-t border-[#cfd5df] py-20 md:grid-cols-[0.8fr_1.2fr] md:py-28"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#bd6d38]">The learning idea</p><h2 className="mt-4 text-4xl font-extrabold tracking-[-0.05em]">Knowledge. Hands On. Fun.</h2></div><div><p className="max-w-2xl text-xl leading-relaxed text-slate-600">Learning should be practical and engaging, with useful knowledge, hands on participation, and an experience that respects the seriousness of workplace learning.</p><Link href="/about-us" className="mt-7 inline-flex text-base font-bold text-[#1d2a63] underline underline-offset-4">Read the profile</Link></div></section>
      <section className="border-t border-[#cfd5df] py-20 md:py-28"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#bd6d38]">Experience and trust</p><h2 className="mt-4 text-4xl font-extrabold tracking-[-0.05em]">A serious learning partner for organizations.</h2></div><Link href="/clients-and-testimonials" className="text-sm font-bold text-[#1d2a63] underline underline-offset-4">View clients</Link></div><div className="mt-12 grid gap-10 border-y border-[#cfd5df] py-8 md:grid-cols-2"><div><p className="text-4xl font-extrabold text-[#1d2a63]">PRIDE</p><p className="mt-2 text-slate-600">Passion, Respect, Innovation, Determination, and Enthusiasm guide the learning experience.</p></div><div><p className="text-4xl font-extrabold text-[#1d2a63]">Past work</p><p className="mt-2 text-slate-600">Explore the past training topics included in the training catalogue.</p></div></div></section>
    </main>
    <section className="bg-[#0e1726] px-5 py-20 text-white sm:px-8 md:py-28"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#e6a16f]">Start a conversation</p><h2 className="mt-4 max-w-2xl text-4xl font-extrabold tracking-[-0.05em] sm:text-5xl">Bring us the capability challenge your teams are facing.</h2></div><Link href="/contact-us" className="inline-flex shrink-0 rounded-full bg-white px-6 py-3 text-sm font-bold text-[#0e1726]">Contact</Link></div></section>
    {jsonLd({ "@context": "https://schema.org", "@type": "WebSite", name: "TraininGenie", url: "https://www.trainingenie.com" })}
  </div>;
}
